// Copyright (c) 2025 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.9
// source: generic/task_scheduler/v1/task_scheduler.proto

package taskscheduler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskSchedulerService_OnJobTriggered_FullMethodName = "/accelbyte.generic.task_scheduler.v1.TaskSchedulerService/OnJobTriggered"
)

// TaskSchedulerServiceClient is the client API for TaskSchedulerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskSchedulerServiceClient interface {
	OnJobTriggered(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecutionContext, Response], error)
}

type taskSchedulerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskSchedulerServiceClient(cc grpc.ClientConnInterface) TaskSchedulerServiceClient {
	return &taskSchedulerServiceClient{cc}
}

func (c *taskSchedulerServiceClient) OnJobTriggered(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecutionContext, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskSchedulerService_ServiceDesc.Streams[0], TaskSchedulerService_OnJobTriggered_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecutionContext, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskSchedulerService_OnJobTriggeredClient = grpc.BidiStreamingClient[ExecutionContext, Response]

// TaskSchedulerServiceServer is the server API for TaskSchedulerService service.
// All implementations should embed UnimplementedTaskSchedulerServiceServer
// for forward compatibility.
type TaskSchedulerServiceServer interface {
	OnJobTriggered(grpc.BidiStreamingServer[ExecutionContext, Response]) error
}

// UnimplementedTaskSchedulerServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskSchedulerServiceServer struct{}

func (UnimplementedTaskSchedulerServiceServer) OnJobTriggered(grpc.BidiStreamingServer[ExecutionContext, Response]) error {
	return status.Error(codes.Unimplemented, "method OnJobTriggered not implemented")
}
func (UnimplementedTaskSchedulerServiceServer) testEmbeddedByValue() {}

// UnsafeTaskSchedulerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskSchedulerServiceServer will
// result in compilation errors.
type UnsafeTaskSchedulerServiceServer interface {
	mustEmbedUnimplementedTaskSchedulerServiceServer()
}

func RegisterTaskSchedulerServiceServer(s grpc.ServiceRegistrar, srv TaskSchedulerServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskSchedulerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskSchedulerService_ServiceDesc, srv)
}

func _TaskSchedulerService_OnJobTriggered_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskSchedulerServiceServer).OnJobTriggered(&grpc.GenericServerStream[ExecutionContext, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskSchedulerService_OnJobTriggeredServer = grpc.BidiStreamingServer[ExecutionContext, Response]

// TaskSchedulerService_ServiceDesc is the grpc.ServiceDesc for TaskSchedulerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskSchedulerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.generic.task_scheduler.v1.TaskSchedulerService",
	HandlerType: (*TaskSchedulerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnJobTriggered",
			Handler:       _TaskSchedulerService_OnJobTriggered_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "generic/task_scheduler/v1/task_scheduler.proto",
}
