// Copyright (c) 2025 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.9
// source: generic/task_scheduler/v1/task_scheduler.proto

package taskscheduler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_TASK_START MessageType = 0
	MessageType_HEART_BEAT MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "TASK_START",
		1: "HEART_BEAT",
	}
	MessageType_value = map[string]int32{
		"TASK_START": 0,
		"HEART_BEAT": 1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_generic_task_scheduler_v1_task_scheduler_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_generic_task_scheduler_v1_task_scheduler_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_generic_task_scheduler_v1_task_scheduler_proto_rawDescGZIP(), []int{0}
}

type ExecutionContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageType    MessageType            `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=accelbyte.generic.task_scheduler.v1.MessageType" json:"message_type,omitempty"`
	CronExpression string                 `protobuf:"bytes,2,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutionContext) Reset() {
	*x = ExecutionContext{}
	mi := &file_generic_task_scheduler_v1_task_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionContext) ProtoMessage() {}

func (x *ExecutionContext) ProtoReflect() protoreflect.Message {
	mi := &file_generic_task_scheduler_v1_task_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionContext.ProtoReflect.Descriptor instead.
func (*ExecutionContext) Descriptor() ([]byte, []int) {
	return file_generic_task_scheduler_v1_task_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionContext) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_TASK_START
}

func (x *ExecutionContext) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_generic_task_scheduler_v1_task_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_generic_task_scheduler_v1_task_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_generic_task_scheduler_v1_task_scheduler_proto_rawDescGZIP(), []int{1}
}

var File_generic_task_scheduler_v1_task_scheduler_proto protoreflect.FileDescriptor

const file_generic_task_scheduler_v1_task_scheduler_proto_rawDesc = "" +
	"\n" +
	".generic/task_scheduler/v1/task_scheduler.proto\x12#accelbyte.generic.task_scheduler.v1\"\x90\x01\n" +
	"\x10ExecutionContext\x12S\n" +
	"\fmessage_type\x18\x01 \x01(\x0e20.accelbyte.generic.task_scheduler.v1.MessageTypeR\vmessageType\x12'\n" +
	"\x0fcron_expression\x18\x02 \x01(\tR\x0ecronExpression\"\n" +
	"\n" +
	"\bResponse*-\n" +
	"\vMessageType\x12\x0e\n" +
	"\n" +
	"TASK_START\x10\x00\x12\x0e\n" +
	"\n" +
	"HEART_BEAT\x10\x012\x92\x01\n" +
	"\x14TaskSchedulerService\x12z\n" +
	"\x0eOnJobTriggered\x125.accelbyte.generic.task_scheduler.v1.ExecutionContext\x1a-.accelbyte.generic.task_scheduler.v1.Response(\x010\x01Bn\n" +
	"#net.accelbyte.generic.taskschedulerP\x01Z#accelbyte.net/generic/taskscheduler\xaa\x02\x1fAccelByte.Generic.TaskSchedulerb\x06proto3"

var (
	file_generic_task_scheduler_v1_task_scheduler_proto_rawDescOnce sync.Once
	file_generic_task_scheduler_v1_task_scheduler_proto_rawDescData []byte
)

func file_generic_task_scheduler_v1_task_scheduler_proto_rawDescGZIP() []byte {
	file_generic_task_scheduler_v1_task_scheduler_proto_rawDescOnce.Do(func() {
		file_generic_task_scheduler_v1_task_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_generic_task_scheduler_v1_task_scheduler_proto_rawDesc), len(file_generic_task_scheduler_v1_task_scheduler_proto_rawDesc)))
	})
	return file_generic_task_scheduler_v1_task_scheduler_proto_rawDescData
}

var file_generic_task_scheduler_v1_task_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_generic_task_scheduler_v1_task_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_generic_task_scheduler_v1_task_scheduler_proto_goTypes = []any{
	(MessageType)(0),         // 0: accelbyte.generic.task_scheduler.v1.MessageType
	(*ExecutionContext)(nil), // 1: accelbyte.generic.task_scheduler.v1.ExecutionContext
	(*Response)(nil),         // 2: accelbyte.generic.task_scheduler.v1.Response
}
var file_generic_task_scheduler_v1_task_scheduler_proto_depIdxs = []int32{
	0, // 0: accelbyte.generic.task_scheduler.v1.ExecutionContext.message_type:type_name -> accelbyte.generic.task_scheduler.v1.MessageType
	1, // 1: accelbyte.generic.task_scheduler.v1.TaskSchedulerService.OnJobTriggered:input_type -> accelbyte.generic.task_scheduler.v1.ExecutionContext
	2, // 2: accelbyte.generic.task_scheduler.v1.TaskSchedulerService.OnJobTriggered:output_type -> accelbyte.generic.task_scheduler.v1.Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_generic_task_scheduler_v1_task_scheduler_proto_init() }
func file_generic_task_scheduler_v1_task_scheduler_proto_init() {
	if File_generic_task_scheduler_v1_task_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_generic_task_scheduler_v1_task_scheduler_proto_rawDesc), len(file_generic_task_scheduler_v1_task_scheduler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_generic_task_scheduler_v1_task_scheduler_proto_goTypes,
		DependencyIndexes: file_generic_task_scheduler_v1_task_scheduler_proto_depIdxs,
		EnumInfos:         file_generic_task_scheduler_v1_task_scheduler_proto_enumTypes,
		MessageInfos:      file_generic_task_scheduler_v1_task_scheduler_proto_msgTypes,
	}.Build()
	File_generic_task_scheduler_v1_task_scheduler_proto = out.File
	file_generic_task_scheduler_v1_task_scheduler_proto_goTypes = nil
	file_generic_task_scheduler_v1_task_scheduler_proto_depIdxs = nil
}
