// Copyright (c) 2025 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.9
// source: task_scheduler/task_scheduler.proto

package taskscheduler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduledTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`                          // Unique run ID for idempotency
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                       // Task definition ID
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`                               // Namespace
	TaskName      string                 `protobuf:"bytes,4,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`                 // Human-readable task name
	ScheduledTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`  // Scheduled run time
	AttemptNumber int32                  `protobuf:"varint,6,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"` // Current attempt number (1-based)
	Payload       string                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`                                   // Task payload (JSON string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduledTaskRequest) Reset() {
	*x = ScheduledTaskRequest{}
	mi := &file_task_scheduler_task_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledTaskRequest) ProtoMessage() {}

func (x *ScheduledTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_scheduler_task_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledTaskRequest.ProtoReflect.Descriptor instead.
func (*ScheduledTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_scheduler_task_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduledTaskRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ScheduledTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ScheduledTaskRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ScheduledTaskRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *ScheduledTaskRequest) GetScheduledTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledTime
	}
	return nil
}

func (x *ScheduledTaskRequest) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *ScheduledTaskRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ScheduledTaskResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                       // Whether the task succeeded
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                        // Optional message or error description
	ResultData     string                 `protobuf:"bytes,3,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`                // Optional result data as JSON object
	HttpStatusCode int32                  `protobuf:"varint,4,opt,name=http_status_code,json=httpStatusCode,proto3" json:"http_status_code,omitempty"` // HTTP-style status code (200, 400, 500, etc.)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScheduledTaskResponse) Reset() {
	*x = ScheduledTaskResponse{}
	mi := &file_task_scheduler_task_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledTaskResponse) ProtoMessage() {}

func (x *ScheduledTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_scheduler_task_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledTaskResponse.ProtoReflect.Descriptor instead.
func (*ScheduledTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_scheduler_task_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduledTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScheduledTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScheduledTaskResponse) GetResultData() string {
	if x != nil {
		return x.ResultData
	}
	return ""
}

func (x *ScheduledTaskResponse) GetHttpStatusCode() int32 {
	if x != nil {
		return x.HttpStatusCode
	}
	return 0
}

var File_task_scheduler_task_scheduler_proto protoreflect.FileDescriptor

const file_task_scheduler_task_scheduler_proto_rawDesc = "" +
	"\n" +
	"#task_scheduler/task_scheduler.proto\x12\"accelbyte.extend.task_scheduler.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x02\n" +
	"\x14ScheduledTaskRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1b\n" +
	"\ttask_name\x18\x04 \x01(\tR\btaskName\x12A\n" +
	"\x0escheduled_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rscheduledTime\x12%\n" +
	"\x0eattempt_number\x18\x06 \x01(\x05R\rattemptNumber\x12\x18\n" +
	"\apayload\x18\a \x01(\tR\apayload\"\x96\x01\n" +
	"\x15ScheduledTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vresult_data\x18\x03 \x01(\tR\n" +
	"resultData\x12(\n" +
	"\x10http_status_code\x18\x04 \x01(\x05R\x0ehttpStatusCode2\xa0\x01\n" +
	"\x14ScheduledTaskHandler\x12\x87\x01\n" +
	"\x10RunScheduledTask\x128.accelbyte.extend.task_scheduler.v1.ScheduledTaskRequest\x1a9.accelbyte.extend.task_scheduler.v1.ScheduledTaskResponseBk\n" +
	"\"net.accelbyte.extend.taskschedulerP\x01Z\"accelbyte.net/extend/taskscheduler\xaa\x02\x1eAccelByte.Extend.TaskSchedulerb\x06proto3"

var (
	file_task_scheduler_task_scheduler_proto_rawDescOnce sync.Once
	file_task_scheduler_task_scheduler_proto_rawDescData []byte
)

func file_task_scheduler_task_scheduler_proto_rawDescGZIP() []byte {
	file_task_scheduler_task_scheduler_proto_rawDescOnce.Do(func() {
		file_task_scheduler_task_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_scheduler_task_scheduler_proto_rawDesc), len(file_task_scheduler_task_scheduler_proto_rawDesc)))
	})
	return file_task_scheduler_task_scheduler_proto_rawDescData
}

var file_task_scheduler_task_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_task_scheduler_task_scheduler_proto_goTypes = []any{
	(*ScheduledTaskRequest)(nil),  // 0: accelbyte.extend.task_scheduler.v1.ScheduledTaskRequest
	(*ScheduledTaskResponse)(nil), // 1: accelbyte.extend.task_scheduler.v1.ScheduledTaskResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_task_scheduler_task_scheduler_proto_depIdxs = []int32{
	2, // 0: accelbyte.extend.task_scheduler.v1.ScheduledTaskRequest.scheduled_time:type_name -> google.protobuf.Timestamp
	0, // 1: accelbyte.extend.task_scheduler.v1.ScheduledTaskHandler.RunScheduledTask:input_type -> accelbyte.extend.task_scheduler.v1.ScheduledTaskRequest
	1, // 2: accelbyte.extend.task_scheduler.v1.ScheduledTaskHandler.RunScheduledTask:output_type -> accelbyte.extend.task_scheduler.v1.ScheduledTaskResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_task_scheduler_task_scheduler_proto_init() }
func file_task_scheduler_task_scheduler_proto_init() {
	if File_task_scheduler_task_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_scheduler_task_scheduler_proto_rawDesc), len(file_task_scheduler_task_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_scheduler_task_scheduler_proto_goTypes,
		DependencyIndexes: file_task_scheduler_task_scheduler_proto_depIdxs,
		MessageInfos:      file_task_scheduler_task_scheduler_proto_msgTypes,
	}.Build()
	File_task_scheduler_task_scheduler_proto = out.File
	file_task_scheduler_task_scheduler_proto_goTypes = nil
	file_task_scheduler_task_scheduler_proto_depIdxs = nil
}
