// Copyright (c) 2025 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.9
// source: task_scheduler/task_scheduler.proto

package taskscheduler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScheduledTaskHandler_RunScheduledTask_FullMethodName = "/accelbyte.extend.task_scheduler.v1.ScheduledTaskHandler/RunScheduledTask"
)

// ScheduledTaskHandlerClient is the client API for ScheduledTaskHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ScheduledTaskHandler service - run by main container to handle scheduled tasks
// This service is implemented by the Extend service's main container
// and called by the Sidecar when a scheduled task needs to be run
type ScheduledTaskHandlerClient interface {
	// RunScheduledTask runs a scheduled task
	// The main container implements this RPC to handle task runs
	RunScheduledTask(ctx context.Context, in *ScheduledTaskRequest, opts ...grpc.CallOption) (*ScheduledTaskResponse, error)
}

type scheduledTaskHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewScheduledTaskHandlerClient(cc grpc.ClientConnInterface) ScheduledTaskHandlerClient {
	return &scheduledTaskHandlerClient{cc}
}

func (c *scheduledTaskHandlerClient) RunScheduledTask(ctx context.Context, in *ScheduledTaskRequest, opts ...grpc.CallOption) (*ScheduledTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduledTaskResponse)
	err := c.cc.Invoke(ctx, ScheduledTaskHandler_RunScheduledTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScheduledTaskHandlerServer is the server API for ScheduledTaskHandler service.
// All implementations should embed UnimplementedScheduledTaskHandlerServer
// for forward compatibility.
//
// ScheduledTaskHandler service - run by main container to handle scheduled tasks
// This service is implemented by the Extend service's main container
// and called by the Sidecar when a scheduled task needs to be run
type ScheduledTaskHandlerServer interface {
	// RunScheduledTask runs a scheduled task
	// The main container implements this RPC to handle task runs
	RunScheduledTask(context.Context, *ScheduledTaskRequest) (*ScheduledTaskResponse, error)
}

// UnimplementedScheduledTaskHandlerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScheduledTaskHandlerServer struct{}

func (UnimplementedScheduledTaskHandlerServer) RunScheduledTask(context.Context, *ScheduledTaskRequest) (*ScheduledTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunScheduledTask not implemented")
}
func (UnimplementedScheduledTaskHandlerServer) testEmbeddedByValue() {}

// UnsafeScheduledTaskHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScheduledTaskHandlerServer will
// result in compilation errors.
type UnsafeScheduledTaskHandlerServer interface {
	mustEmbedUnimplementedScheduledTaskHandlerServer()
}

func RegisterScheduledTaskHandlerServer(s grpc.ServiceRegistrar, srv ScheduledTaskHandlerServer) {
	// If the following call panics, it indicates UnimplementedScheduledTaskHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScheduledTaskHandler_ServiceDesc, srv)
}

func _ScheduledTaskHandler_RunScheduledTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduledTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduledTaskHandlerServer).RunScheduledTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduledTaskHandler_RunScheduledTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduledTaskHandlerServer).RunScheduledTask(ctx, req.(*ScheduledTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScheduledTaskHandler_ServiceDesc is the grpc.ServiceDesc for ScheduledTaskHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScheduledTaskHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.extend.task_scheduler.v1.ScheduledTaskHandler",
	HandlerType: (*ScheduledTaskHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunScheduledTask",
			Handler:    _ScheduledTaskHandler_RunScheduledTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task_scheduler/task_scheduler.proto",
}
