// Copyright (c) 2023 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.9
// source: service.proto

package serviceextension

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTaskExecutionCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskExecutionCountRequest) Reset() {
	*x = GetTaskExecutionCountRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskExecutionCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskExecutionCountRequest) ProtoMessage() {}

func (x *GetTaskExecutionCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskExecutionCountRequest.ProtoReflect.Descriptor instead.
func (*GetTaskExecutionCountRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type GetTaskExecutionCountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The total count of task executions.
	Count         int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskExecutionCountResponse) Reset() {
	*x = GetTaskExecutionCountResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskExecutionCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskExecutionCountResponse) ProtoMessage() {}

func (x *GetTaskExecutionCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskExecutionCountResponse.ProtoReflect.Descriptor instead.
func (*GetTaskExecutionCountResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetTaskExecutionCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\aservice\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x1e\n" +
	"\x1cGetTaskExecutionCountRequest\"5\n" +
	"\x1dGetTaskExecutionCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count2\x87\x02\n" +
	"\aService\x12\xfb\x01\n" +
	"\x15GetTaskExecutionCount\x12%.service.GetTaskExecutionCountRequest\x1a&.service.GetTaskExecutionCountResponse\"\x92\x01\x92Ak\x12 Get the count of task executions\x1aGRetrieves the total number of task executions processed by the service.\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/tasks/execution/countB\x95\x01\x92A\x1e\x12\x12\n" +
	"\vService API2\x031.0\"\b/service\n" +
	"%net.accelbyte.extend.serviceextensionP\x01Z%accelbyte.net/extend/serviceextension\xaa\x02!AccelByte.Extend.ServiceExtensionb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_proto_goTypes = []any{
	(*GetTaskExecutionCountRequest)(nil),  // 0: service.GetTaskExecutionCountRequest
	(*GetTaskExecutionCountResponse)(nil), // 1: service.GetTaskExecutionCountResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: service.Service.GetTaskExecutionCount:input_type -> service.GetTaskExecutionCountRequest
	1, // 1: service.Service.GetTaskExecutionCount:output_type -> service.GetTaskExecutionCountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
